In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Loading data
df = pd.read_csv('/content/portugal_listinigs.csv')

<ipython-input-4-df672bca5cea>:2: DtypeWarning: Columns (6,8,12,13,14,15,16,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/portugal_listinigs.csv')

In [5]:
# Menampilkan 5 data teratas
df.head(5)

,Price,District,City,Town,Type,EnergyCertificate,Floor,Parking,HasParking,ConstructionYear,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
0,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,2nd Floor,1.0,True,NaN,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,2.0
1,9500.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,NC,1st Floor,0.0,False,1990.0,...,True,NaN,0.0,NaN,NaN,NaN,27.0,NaN,NaN,1.0
2,580000.0,Faro,Vila do Bispo,Budens,Apartment,D,3rd Floor,1.0,True,2003.0,...,False,NaN,2.0,NaN,NaN,NaN,84.0,NaN,NaN,2.0
3,350000.0,Faro,Portimão,Portimão,Apartment,C,4th Floor,0.0,False,1985.0,...,True,NaN,2.0,NaN,NaN,NaN,68.0,NaN,NaN,1.0
4,175000.0,Faro,Faro,Faro (Sé e São Pedro),House,NC,NaN,0.0,False,1950.0,...,False,NaN,4.0,NaN,NaN,NaN,78.0,NaN,NaN,2.0

In [6]:
# Cek Missing Value
df.isnull()

,Price,District,City,Town,Type,EnergyCertificate,Floor,Parking,HasParking,ConstructionYear,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
0,False,False,False,False,False,False,False,False,False,True,...,False,True,False,True,True,True,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,True,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,True,True,False
4,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129832,False,False,False,False,False,False,True,False,True,False,...,False,False,True,False,False,True,False,True,False,False
129833,False,False,False,False,False,False,True,False,True,True,...,False,False,True,True,True,True,True,False,True,True
129834,False,False,False,False,False,False,True,False,True,False,...,False,False,True,False,False,True,False,True,True,False
129835,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
129836,False,False,False,False,False,False,True,False,True,False,...,False,False,True,False,False,True,False,True,False,False

In [7]:
# Informasi struktur data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129837 entries, 0 to 129836
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Price                  129541 non-null  float64
 1   District               129837 non-null  object
 2   City                   129837 non-null  object
 3   Town                   129835 non-null  object
 4   Type                   129821 non-null  object
 5   EnergyCertificate      129823 non-null  object
 6   Floor                  27929 non-null   object
 7   Parking                129643 non-null  float64
 8   HasParking             68215 non-null   object
 9   ConstructionYear       84354 non-null   float64
 10  TotalArea              121922 non-null  float64
 11  GrossArea              27638 non-null   float64
 12  EnergyEfficiencyLevel  61590 non-null   object
 13  PublishDate            25195 non-null   object
 14  Garage                 61590 non-null   object
 15  Elevator               129805 non-null  object
 16  ElectricCarsCharging   61590 non-null   object
 17  TotalRooms             71387 non-null   float64
 18  NumberOfBedrooms       42478 non-null   float64
 19  NumberOfWC             53331 non-null   float64
 20  ConservationStatus     17754 non-null   object
 21  LivingArea             100054 non-null  float64
 22  LotSize                36582 non-null   float64
 23  BuiltArea              24644 non-null   float64
 24  NumberOfBathrooms      123393 non-null  float64
dtypes: float64(12), object(13)
memory usage: 24.8+ MB

In [19]:
# MENGUBAH TIPE DATA

# Mengubah tipe data kolom HasParking to bool
df['HasParking'] = df['HasParking'].astype(bool)

# Mengubah tipe data kolom Garage to bool
df['Garage'] = df['Garage'].astype(bool)

# Mengubah tipe data kolom Elevator to bool
df['Elevator'] = df['Elevator'].astype(bool)

# Mengubah tipe data kolom ElectricCarsCharging to bool
df['ElectricCarsCharging'] = df['ElectricCarsCharging'].astype(bool)

# Mengubah tipe data kolom PublishDate to datetime
df['PublishDate'] = pd.to_datetime(df['PublishDate'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

# Mengubah tipe data kolom ConstructionYear to datetime
df['ConstructionYear'] = pd.to_datetime(df['ConstructionYear'], format='%Y', errors='coerce')
print(df.dtypes)

Price                           float64
District                         object
City                             object
Town                             object
Type                             object
EnergyCertificate                object
Floor                            object
Parking                          object
HasParking                         bool
ConstructionYear         datetime64[ns]
TotalArea                       float64
GrossArea                       float64
EnergyEfficiencyLevel            object
PublishDate              datetime64[ns]
Garage                             bool
Elevator                           bool
ElectricCarsCharging               bool
TotalRooms                      float64
NumberOfBedrooms                float64
NumberOfWC                      float64
ConservationStatus               object
LivingArea                      float64
LotSize                         float64
BuiltArea                       float64
NumberOfBathrooms               float64
dtype: object

In [20]:
# Hitung total nilai yang hilang per kolom
missing_counts = df.isnull().sum()

# Hitung persentase nilai yang hilang per kolom
missing_percentage = (missing_counts / len(df)) * 100

# Gabungkan hasil menjadi DataFrame
missing_summary = pd.DataFrame({
    'Missing Count': missing_counts,
    'Missing Percentage (%)': missing_percentage
})

print(missing_summary)

                       Missing Count  Missing Percentage (%)
Price                              0                0.000000
District                           0                0.000000
City                               0                0.000000
Town                               0                0.000000
Type                               0                0.000000
EnergyCertificate                  0                0.000000
Floor                          95545               78.544770
Parking                            0                0.000000
HasParking                         0                0.000000
ConstructionYear                   0                0.000000
TotalArea                          0                0.000000
GrossArea                      95630               78.614646
EnergyEfficiencyLevel          63911               52.539377
PublishDate                   121384               99.786262
Garage                             0                0.000000
Elevator                           0                0.000000
ElectricCarsCharging               0                0.000000
TotalRooms                         0                0.000000
NumberOfBedrooms               81872               67.304594
NumberOfWC                     71753               58.986058
ConservationStatus            105008               86.324027
LivingArea                         0                0.000000
LotSize                        87310               71.775016
BuiltArea                      98530               80.998652
NumberOfBathrooms                  0                0.000000

In [22]:
# Mengisi missing values dengan strategi yang ditentukan
df['Price'] = df['Price'].fillna(df['Price'].median())
df['Town'] = df['Town'].fillna(method='ffill')
df['Type'] = df['Type'].fillna(df['Type'].mode()[0])
df['EnergyCertificate'] = df['EnergyCertificate'].fillna('Unknown')
df['Parking'] = df['Parking'].fillna('None')
df['Elevator'] = df['Elevator'].fillna(False)
df['NumberOfBathrooms'] = df['NumberOfBathrooms'].fillna(df['NumberOfBathrooms'].median())

df['HasParking'] = df['HasParking'].fillna(False)
df['ConstructionYear'] = df['ConstructionYear'].fillna(df['ConstructionYear'].median())
df['TotalArea'] = df['TotalArea'].fillna(df['TotalArea'].median())
df['TotalRooms'] = df['TotalRooms'].fillna(df['TotalRooms'].median())
df['LivingArea'] = df['LivingArea'].fillna(df['LivingArea'].median())

# Ekstraksi angka dari kolom 'Floor' menggunakan str.extract
df['Floor'] = df['Floor'].str.extract('(\d+)').astype(float)

# Imputasi nilai missing dengan median
df['Floor'] = df['Floor'].fillna(df['Floor'].median())

df['GrossArea'] = df['GrossArea'].fillna(df['GrossArea'].median())
df['EnergyEfficiencyLevel'] = df['EnergyEfficiencyLevel'].fillna('Unknown')
df['Garage'] = df['Garage'].fillna('None')
df['ElectricCarsCharging'] = df['ElectricCarsCharging'].fillna(False)
df['NumberOfBedrooms'] = df['NumberOfBedrooms'].fillna(df['NumberOfBedrooms'].median())
df['NumberOfWC'] = df['NumberOfWC'].fillna(df['NumberOfWC'].median())
df['LotSize'] = df['LotSize'].fillna(df['LotSize'].median())


# Verifikasi hasil
df.isnull().sum()

<ipython-input-22-0e6db2841618>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Town'] = df['Town'].fillna(method='ffill')

Price                         0
District                      0
City                          0
Town                          0
Type                          0
EnergyCertificate             0
Floor                         0
Parking                       0
HasParking                    0
ConstructionYear              0
TotalArea                     0
GrossArea                     0
EnergyEfficiencyLevel         0
PublishDate              121384
Garage                        0
Elevator                      0
ElectricCarsCharging          0
TotalRooms                    0
NumberOfBedrooms              0
NumberOfWC                    0
ConservationStatus       105008
LivingArea                    0
LotSize                       0
BuiltArea                 98530
NumberOfBathrooms             0
dtype: int64

In [11]:
# Cek data duplicate
duplicates = df.duplicated()
duplicates

0         False
1         False
2         False
3         False
4         False
          ...
129832     True
129833    False
129834    False
129835    False
129836    False
Length: 129837, dtype: bool

In [12]:
# Counting data duplicate
duplicates = df.duplicated().sum()
duplicates

8193

In [13]:
df = df.drop_duplicates()
df

,Price,District,City,Town,Type,EnergyCertificate,Floor,Parking,HasParking,ConstructionYear,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
0,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,2nd Floor,1.0,True,1994.0,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,2.0
1,9500.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,NC,1st Floor,0.0,False,1990.0,...,True,NaN,0.0,NaN,NaN,NaN,27.0,NaN,NaN,1.0
2,580000.0,Faro,Vila do Bispo,Budens,Apartment,D,3rd Floor,1.0,True,2003.0,...,False,NaN,2.0,NaN,NaN,NaN,84.0,NaN,NaN,2.0
3,350000.0,Faro,Portimão,Portimão,Apartment,C,4th Floor,0.0,False,1985.0,...,True,NaN,2.0,NaN,NaN,NaN,68.0,NaN,NaN,1.0
4,175000.0,Faro,Faro,Faro (Sé e São Pedro),House,NC,NaN,0.0,False,1950.0,...,False,NaN,4.0,NaN,NaN,NaN,78.0,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129831,50000.0,Vila Real,Peso da Régua,Sedielos,House,F,NaN,0.0,False,1974.0,...,False,False,3.0,3.0,0.0,NaN,130.0,250.0,NaN,0.0
129833,75000.0,Vila Real,Vila Real,Folhadela,Land,NC,NaN,0.0,False,1994.0,...,False,False,3.0,NaN,NaN,NaN,120.0,600.0,NaN,1.0
129834,35000.0,Vila Real,Peso da Régua,Loureiro,House,F,NaN,0.0,False,1951.0,...,False,False,3.0,2.0,0.0,NaN,64.0,NaN,NaN,1.0
129835,185000.0,Vila Real,Sabrosa,Sabrosa,House,E,NaN,0.0,False,1991.0,...,False,False,16.0,4.0,2.0,Good condition,260.0,210.0,260.0,3.0
129836,125000.0,Vila Real,Peso da Régua,Peso da Régua e Godim,House,D,NaN,0.0,False,1991.0,...,False,False,3.0,4.0,0.0,NaN,203.0,NaN,203.0,0.0

In [14]:
# Cek after data duplicate
duplicates = df.duplicated().sum()
duplicates

0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 121644 entries, 0 to 129836
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Price                  121644 non-null  float64
 1   District               121644 non-null  object
 2   City                   121644 non-null  object
 3   Town                   121644 non-null  object
 4   Type                   121644 non-null  object
 5   EnergyCertificate      121644 non-null  object
 6   Floor                  26099 non-null   object
 7   Parking                121644 non-null  object
 8   HasParking             121644 non-null  bool
 9   ConstructionYear       121644 non-null  float64
 10  TotalArea              121644 non-null  float64
 11  GrossArea              26014 non-null   float64
 12  EnergyEfficiencyLevel  57733 non-null   object
 13  PublishDate            24206 non-null   object
 14  Garage                 57733 non-null   object
 15  Elevator               121644 non-null  bool
 16  ElectricCarsCharging   57733 non-null   object
 17  TotalRooms             121644 non-null  float64
 18  NumberOfBedrooms       39772 non-null   float64
 19  NumberOfWC             49891 non-null   float64
 20  ConservationStatus     16636 non-null   object
 21  LivingArea             121644 non-null  float64
 22  LotSize                34334 non-null   float64
 23  BuiltArea              23114 non-null   float64
 24  NumberOfBathrooms      121644 non-null  float64
dtypes: bool(2), float64(11), object(12)
memory usage: 22.5+ MB

In [16]:
# MENGUBAH TIPE DATA

# Mengubah tipe data kolom HasParking to bool
df['HasParking'] = df['HasParking'].astype(bool)

# Mengubah tipe data kolom Garage to bool
df['Garage'] = df['Garage'].astype(bool)

# Mengubah tipe data kolom Elevator to bool
df['Elevator'] = df['Elevator'].astype(bool)

# Mengubah tipe data kolom ElectricCarsCharging to bool
df['ElectricCarsCharging'] = df['ElectricCarsCharging'].astype(bool)

# Mengubah tipe data kolom PublishDate to datetime
df['PublishDate'] = pd.to_datetime(df['PublishDate'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

# Mengubah tipe data kolom ConstructionYear to datetime
df['ConstructionYear'] = pd.to_datetime(df['ConstructionYear'], format='%Y', errors='coerce')
print(df.dtypes)

Price                           float64
District                         object
City                             object
Town                             object
Type                             object
EnergyCertificate                object
Floor                            object
Parking                          object
HasParking                         bool
ConstructionYear         datetime64[ns]
TotalArea                       float64
GrossArea                       float64
EnergyEfficiencyLevel            object
PublishDate              datetime64[ns]
Garage                             bool
Elevator                           bool
ElectricCarsCharging               bool
TotalRooms                      float64
NumberOfBedrooms                float64
NumberOfWC                      float64
ConservationStatus               object
LivingArea                      float64
LotSize                         float64
BuiltArea                       float64
NumberOfBathrooms               float64
dtype: object

In [17]:
df.head()

,Price,District,City,Town,Type,EnergyCertificate,Floor,Parking,HasParking,ConstructionYear,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
0,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,2nd Floor,1.0,True,1994-01-01,...,True,True,2.0,NaN,NaN,NaN,114.0,NaN,NaN,2.0
1,9500.0,Faro,Albufeira,Albufeira e Olhos de Água,Apartment,NC,1st Floor,0.0,False,1990-01-01,...,True,True,0.0,NaN,NaN,NaN,27.0,NaN,NaN,1.0
2,580000.0,Faro,Vila do Bispo,Budens,Apartment,D,3rd Floor,1.0,True,2003-01-01,...,False,True,2.0,NaN,NaN,NaN,84.0,NaN,NaN,2.0
3,350000.0,Faro,Portimão,Portimão,Apartment,C,4th Floor,0.0,False,1985-01-01,...,True,True,2.0,NaN,NaN,NaN,68.0,NaN,NaN,1.0
4,175000.0,Faro,Faro,Faro (Sé e São Pedro),House,NC,NaN,0.0,False,1950-01-01,...,False,True,4.0,NaN,NaN,NaN,78.0,NaN,NaN,2.0

In [23]:
# Menyimpan data to csv
df.to_csv('coda_P1GC4_portugal_listinigs.csv', index=False)